[Definition]
failregex = ^\s*\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} \[info\] \d+#\d+: \*\d+ client sent invalid method while reading client request line, client: <HOST>, server:
            ^\s*\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} \[info\] \d+#\d+: \*\d+ client sent invalid request while reading client request line, client: <HOST>, server:
            ^\s*\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} \[info\] \d+#\d+: \*\d+ client sent HTTP/1\.1 request without "Host" header while reading client request headers, client: <HOST>, server:
ignoreregex =
