server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_tokens off;
    server_name _;
    return 444;   # or: return 404;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_tokens off;
    server_name _;
    ssl_reject_handshake on;   # abort TLS before sending certificate
}
